services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8005:8000
    depends_on:
      - db
    env_file:
      - docker.env
    networks:
      docker_network:
    
  db:
    image: postgres:16.4-alpine
    ports:
      - 5434:5432
    environment:
        POSTGRES_DB: catalystmediadb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
    volumes:
      - my_Data:/var/lib/postgresql/data
    networks:
      docker_network:

volumes:
  my_Data:


networks:
  docker_network:
    driver: bridge    

    