FROM python:3.10

ENV PYTHONUNBUFFERED=1

WORKDIR /CatalystMediaTask

COPY . /CatalystMediaTask
COPY requirements.txt /CatalystMediaTask

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /CatalystMediaTask

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]